# Generated by Django 4.1.4 on 2022-12-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_next',
            new_name='choice_text',
        ),
    ]
